apiVersion: v1
kind: Service
metadata:
  name: nop-commerce-service
  namespace: devnamespace
  labels:
    app: nop-commerce
spec:
  type: LoadBalancer
  selector:
    app: nop-commerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000