name: mydonet project

on: 
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
             -Dsonar.organization=nikhitha-git17
             -Dsonar.projectKey=nikhitha-git17_nopCommerce
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Publish .NET project
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o sravs
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        env:
          ECR_REPOSITORY: githubrepo
          IMAGE_TAG: latest
        run: |
          docker build -t githubrepo .
          docker tag githubrepo:latest 137764817332.dkr.ecr.ap-south-1.amazonaws.com/githubrepo:latest
          docker push 137764817332.dkr.ecr.ap-south-1.amazonaws.com/githubrepo:latest
            
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --name hilarious-mongoose-1762925037 --region ap-south-1
      
      - name: creating and switching namespaces
        run: |
          kubectl create namespace devnamespace --dry-run=client -o yaml | kubectl apply -f -
          kubectl config set-context --current --namespace devnamespace
  
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/nop-commerce-deployment
          kubectl get svc
