name: mydonet project

on: 
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
             -Dsonar.organization=nikhitha-git17
             -Dsonar.projectKey=nikhitha-git17_nopCommerce
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Publish .NET project
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o sravs
