name: mydotnet project

on:
  push:
    branches:
      - develop 
jobs:
  dotnet_publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: code checkout
        uses: actions/checkout@v5
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v2
      - name: build and push
        uses: docker/build-push-action@v6
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 137764817332.dkr.ecr.ap-south-1.amazonaws.com
          docker image build -t dotnet:1.0 .
          docker image tag dotnet:1.0 137764817332.dkr.ecr.ap-south-1.amazonaws.com/dummyrepo:latest
          docker push 137764817332.dkr.ecr.ap-south-1.amazonaws.com/dummyrepo:latest
      - name: EKS with manifestfile
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - uses: tale/kubectl-action@v1
      - run: |
          kubectl apply -f .
          kubectl get po
              